*标量*，维度为0，shape为[]

In [4]:
import tensorflow as tf


a = tf.constant(1.6)
print(f'标量：{a}')

标量：1.600000023841858


*向量*，维度为1，shape为[n]

In [6]:
a = tf.constant([1.7, 2, 3.])
print('向量：', a)
print('向量返回Numpy.array类型数据：', a.numpy())

向量： tf.Tensor([1.7 2.  3. ], shape=(3,), dtype=float32)
向量返回Numpy.array类型数据： [1.7 2.  3. ]


*矩阵*，维度为2， shape为[n, m]

In [7]:
a = tf.constant([[1.3, 1.4, 4], [8.9, 91.1, 12], [12, 13.1, 18.9]])
print('矩阵：', a)

矩阵： tf.Tensor(
[[ 1.3  1.4  4. ]
 [ 8.9 91.1 12. ]
 [12.  13.1 18.9]], shape=(3, 3), dtype=float32)


*三维的张量*

In [8]:
a = tf.constant([[[1.2, 1.3], [1.4, 1.5]],
                 [[1.6, 1.7], [1.8, 1.9]],
                 [[1.9, 2.], [2.1, 2.2]]])
print('维度为3的张量：', a)

维度为3的张量： tf.Tensor(
[[[1.2 1.3]
  [1.4 1.5]]

 [[1.6 1.7]
  [1.8 1.9]]

 [[1.9 2. ]
  [2.1 2.2]]], shape=(3, 2, 2), dtype=float32)


查看当前使用的设备类型

In [9]:
with tf.device("cpu"):
    a = tf.constant([1])
    print(a.device)

with tf.device("gpu"):
    b = tf.constant([1])
    print(b.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
