# 创建张量，使用tf.convert_to_tensor()

## 1.从列表创建张量

In [1]:
import tensorflow as tf
import numpy as np

a = tf.convert_to_tensor([1, 2.1, 3.])
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2.1, 3. ], dtype=float32)>

## 2.从数组创建张量  
**需要注意的是 Numpy 浮点数数组默认使用 64 位精度**

In [4]:
a = tf.convert_to_tensor(np.array([[1.2, 2.3], [1., 4.3]]))
print('从数组创建张量:', a, '\n数据精度:', a.dtype)

从数组创建张量: tf.Tensor(
[[1.2 2.3]
 [1.  4.3]], shape=(2, 2), dtype=float64) 
数据精度: <dtype: 'float64'>


## 3.创建全0或者全1的张量

In [8]:
a = tf.zeros([2, 3])
print('\n全0张量:', a)
a = tf.ones([5])
print('\n全1张量', a)


全0张量: tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

全1张量 tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)


## 4.通过tf.zeros_like、tf.ones_like创建与某个张量shape一致的全零或者全1张量

In [13]:
a = tf.constant([[1.2, 1.4, 1.], [5., 4.1, 2.9]])
print('a.shape:', a.shape)
a = tf.ones_like(a)
print('\nshape一致全1张量:', a)

a.shape: (2, 3)

shape一致全1张量: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


## 5.创建自定义数值的张量，使用tf.fill()

In [15]:
a = tf.fill([3, 4], 6)
print('\n自定义数值的张量:', a)


自定义数值的张量: tf.Tensor(
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]], shape=(3, 4), dtype=int32)


## 6.创建已知分布的张量  
正态分布(Normal Distribution，或 Gaussian Distribution)和均匀分布(Uniform Distribution)是最常见的分布之一，  
创建采样自这 2 种分布的张量非常有用，比如在卷积神经网络中，*卷积核张量 𝑾 初始化为正态分布有利于网络的训练*；  
在对抗生成网络中，隐藏 变量𝒛一般采样自均匀分布。


In [17]:
# 标准正态分布张量
a = tf.random.normal([3, 2])
print('标准正态分布:', a)

标准正态分布: tf.Tensor(
[[ 0.9627429  -0.04575269]
 [ 0.69807976  0.9702247 ]
 [ 0.93360984  0.67084306]], shape=(3, 2), dtype=float32)


In [20]:
# 创建均值为1，标准差为2的正态分布
a = tf.random.normal([2, 2], mean=1, stddev=2)
print('创建均值为1，标准差为2的正态分布:', a)

创建均值为1，标准差为2的正态分布: tf.Tensor(
[[0.92041326 1.6248424 ]
 [1.8350005  1.963929  ]], shape=(2, 2), dtype=float32)


In [22]:
# 创建采样自 [ minval , maxval ) 区间的均匀分布的张量
# 通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)
a = tf.random.uniform([16, 2], minval=0, maxval=2)
print('区间均匀分布张量:', a)

区间均匀分布张量: tf.Tensor(
[[0.40760446 0.63620687]
 [0.5807817  0.6380956 ]
 [1.8511136  0.09884214]
 [0.07362533 0.18694639]
 [1.921824   0.21610999]
 [0.4174006  1.0502517 ]
 [0.3219154  0.5515988 ]
 [1.9558632  1.9493649 ]
 [0.33834195 0.6116946 ]
 [1.1525843  1.8257117 ]
 [1.1439145  1.4122679 ]
 [1.3405282  0.8324263 ]
 [1.9292591  0.06757593]
 [0.19034743 1.2139523 ]
 [1.8894548  0.12555313]
 [1.4419518  1.0697618 ]], shape=(16, 2), dtype=float32)


In [25]:
# 指定区间中均匀采样整形类型张量
a = tf.random.uniform([3, 2],maxval=100, dtype=tf.int32)
print('整形均匀分布张量:', a)

整形均匀分布张量: tf.Tensor(
[[83 50]
 [16  7]
 [52 52]], shape=(3, 2), dtype=int32)


In [27]:
# 创建序列
# 通过 tf.range(start, limit, delta=1)可以创建 [ start , limit ) ，步长为 delta 的序列，不包含 limit 本身
a = tf.range(1, 100, 2)
print('[1, 100)步长为2的序列:', a)

[1, 100)步长为2的序列: tf.Tensor(
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99], shape=(50,), dtype=int32)
