# 数学运算

## 1.加、减、乘、除运算

加、减、乘、除是最基本的数学运算，分别通过 tf.add, tf.subtract, tf.multiply, tf.divide
函数实现，TensorFlow 已经重载了+、 − 、 ∗ 、/运算符，一般推荐直接使用运算符来完成
加、减、乘、除运算。
整除和余除也是常见的运算之一，分别通过//和%运算符实现。我们来演示整除运算

In [ ]:
import tensorflow as tf

a = tf.range(5)
b = tf.constant(2)
a // b  # 整除运算

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2], dtype=int32)>

In [ ]:
a % b  # 余除运算

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0], dtype=int32)>

## 2.乘方运算

通过 tf.pow(x, a)可以方便地完成𝑦 = 
𝑎的乘方运算，也可以通过运算符**实现 ∗∗ 𝑎运
算

In [7]:
x = tf.range(4)
tf.pow(x, 3)  # 乘方运算

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [8]:
x**2  # 乘方运算符

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 4, 9], dtype=int32)>

设置指数为1/𝑎
形式，即可实现𝑎
√ 根号运算，例如:

In [9]:
x = tf.constant([1., 4., 9.])
x ** 0.5


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

特别地，对于常见的平方和平方根运算，可以使用 tf.square(x)和 tf.sqrt(x)实现。平方运算
实现如下

In [ ]:
x = tf.range(5)
x = tf.cast(x, tf.float32)
x = tf.square(x)  # 平方
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [11]:
x = tf.sqrt(x)  # 平方根
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

## 3.指数和对数运算

通过 tf.pow(a, x)或者**运算符也可以方便地实现指数运算𝑎^x

In [12]:
x = tf.constant([1., 2., 3.])
2 ** x

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 8.], dtype=float32)>

特别地，对于自然指数e^𝑥，可以通过 tf.exp(x)实现

In [13]:
tf.exp(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

自然对数loge x 可以通过 tf.math.log(x)实现，

In [18]:
x = tf.exp(3.)
tf.math.log(x)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

如果希望计算其它底数的对数，可以根据对数的换底公式
$$
\log_a x = \frac{\log_e x}{\log_e a}
$$

In [20]:
x = tf.constant([1., 2.])
x = 10 ** x

tf.math.log(x) / tf.math.log(10.)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

## 4.矩阵相乘运算  
神经网络中间包含了大量的矩阵相乘运算，前面我们已经介绍了通过@运算符可以方便的实现矩阵相乘，还可以通过 tf.matmul(a, b)函数实现。需要注意的是，TensorFlow 中的
矩阵相乘可以使用批量方式，也就是张量𝑨和𝑩的维度数可以大于 2。当张量𝑨和𝑩维度数大
于 2 时，**TensorFlow 会选择𝑨和𝑩的最后两个维度进行矩阵相乘，前面所有的维度都视作Batch 维度**。  


根据矩阵相乘的定义，𝑨和𝑩能够矩阵相乘的条件是，**𝑨的倒数第一个维度长度(列)和𝑩的倒数第二个维度长度(行)必须相等**。比如张量 a shape:[4,3,28,32]可以与张量 b
shape:[4,3,32,2]进行矩阵相乘，代码如下

In [23]:
a = tf.random.normal([4, 3, 28, 32])
b = tf.random.normal([4, 3, 32, 2])
(a @ b).shape  # 批量形式的矩阵相乘

TensorShape([4, 3, 28, 2])

In [24]:
# 矩阵相乘函数同样支持自动 Broadcasting 机制，例:
a = tf.random.normal([4, 28, 32])
b = tf.random.normal([32, 16])
(a @ b).shape  # 先自动扩展、再矩阵相乘

TensorShape([4, 28, 16])