# 张量比较  
为了计算分类任务的准确率等指标，一般需要将预测结果和真实标签比较，统计比较
结果中正确的数量来计算准确率。  
考虑 100 个样本的预测结果，通过 tf.argmax 获取预测类别，实现如下：

In [8]:
import tensorflow as tf

out = tf.random.normal([100, 10])
out = tf.nn.softmax(out, axis=1)  # 将输出转换为概率
pred = tf.argmax(out, axis=1)  # 计算预测值
pred

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([7, 2, 1, 0, 4, 8, 0, 6, 3, 5, 0, 8, 4, 6, 1, 6, 9, 0, 2, 0, 5, 2,
       2, 4, 7, 2, 3, 6, 3, 2, 2, 5, 8, 1, 2, 7, 5, 7, 3, 1, 4, 7, 1, 6,
       9, 5, 3, 7, 3, 6, 3, 9, 0, 5, 8, 4, 8, 2, 3, 0, 3, 7, 4, 8, 0, 7,
       3, 1, 7, 7, 8, 9, 5, 9, 4, 4, 4, 3, 3, 3, 4, 3, 3, 3, 7, 9, 1, 0,
       6, 4, 1, 3, 3, 3, 0, 4, 7, 7, 4, 7])>

变量 pred 保存了这 100 个样本的预测类别值，我们与这 100 样本的真实标签比较

In [11]:
y = tf.random.uniform([100], maxval=10, dtype=tf.int64)
y


<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([4, 1, 8, 4, 5, 8, 9, 4, 6, 6, 7, 9, 1, 1, 9, 2, 8, 5, 6, 6, 0, 0,
       5, 7, 7, 1, 3, 4, 9, 4, 2, 3, 0, 7, 8, 6, 0, 8, 1, 8, 3, 4, 0, 5,
       9, 3, 4, 9, 0, 1, 4, 8, 9, 0, 1, 2, 5, 0, 2, 3, 2, 3, 8, 5, 7, 4,
       0, 8, 3, 1, 2, 5, 3, 6, 2, 9, 6, 7, 3, 4, 3, 3, 9, 0, 7, 0, 9, 6,
       9, 2, 6, 2, 3, 1, 2, 0, 8, 0, 7, 4])>

## 1.比较2张量是否相等 tf.equal(a, b)  
即可获得代表每个样本是否预测正确的布尔类型张量。通过 tf.equal(a, b)(或 tf.math.equal(a, 
b)，两者等价)函数可以比较这 2 个张量是否相等

In [13]:
out = tf.equal(pred, y)
out

<tf.Tensor: shape=(100,), dtype=bool, numpy=
array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False])>

tf.equal()函数返回布尔类型的张量比较结果，只需要统计张量中 True 元素的个数，即可知
道预测正确的个数。为了达到这个目的，我们先将布尔类型转换为整形张量，即 True 对应
为 1，False 对应为 0，再求和其中 1 的个数，就可以得到比较结果中 True 元素的个数

In [14]:
out  =tf.cast(out, tf.int32)
correct = tf.reduce_sum(out)
correct

<tf.Tensor: shape=(), dtype=int32, numpy=9>

| 函数 | 比较逻辑 |
| --- | --- |
| tf.math.greater | $a > b$ |
| tf.math.less | $a < b$ |
| tf.math.greater_equal | $a \ge b$ |
| tf.math.less_equal | $a \le b$ |
| tf.math.not_equal | $a \ne b$ |
| tf.math.is_nan | $a = \text{nan}$ |