# 5.5 数据限幅

考虑怎么实现非线性激活函数 ReLU 的问题。它其实可以通过简单的数据限幅运算实
现，限制元素的范围𝑥 ∈ [0, +∞)即可。
在 TensorFlow 中，可以通过 tf.maximum(x, a)实现数据的下限幅，即𝑥 ∈ [𝑎, +∞)；可
以通过 tf.minimum(x, a)实现数据的上限幅，即𝑥 ∈ (−∞,𝑎]，举例如下

## 1.数据的下限幅 tf.maximum(x, a)

In [ ]:
import tensorflow as tf

x = tf.range(9)
tf.maximum(x, 2)  # 下限幅到2


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

## 2.数据的上限幅 tf.minimum(x, a)

In [ ]:
tf.minimum(x, 7)  # 上限幅到7

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 7], dtype=int32)>

In [13]:
# 基于 tf.maximum 函数，我们可以实现 ReLU 函数如下
def relu(x):
    return tf.maximum(x, 0.)


x = tf.random.uniform([9], dtype=tf.float32) * 2 - 1
relu(x)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.20589447, 0.7711034 , 0.        , 0.7334018 , 0.76627517,
       0.2536342 , 0.        , 0.        , 0.        ], dtype=float32)>

## 3.同时上下边界限幅 tf.clip_by_value(x,2,7)\tf.minimum(tf.maximum(x, 2), 7) 限幅为2-7

通过组合tf.maximum(x,a)和 tf.minimum(x, b)可以实现同时对数据的上下边界限幅，即X ∈ [a, b]

In [14]:
x = tf.range(9)
tf.minimum(tf.maximum(x, 2), 7)  # 限幅为2-7

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7], dtype=int32)>

**更方便地，我们可以使用 tf.clip_by_value 函数实现上下限幅**

In [15]:
tf.clip_by_value(x, 2, 7)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7], dtype=int32)>