# 8.1 常见功能模块

Keras 提供了一系列高层的神经网络相关类和函数，如经典数据集加载函数、网络层
类、模型容器、损失函数类、优化器类、经典模型类等。
对于经典数据集，通过一行代码即可下载、管理、加载数据集，这些数据集包括
Boston 房价预测数据集、CIFAR 图片数据集、MNIST/FashionMNIST 手写数字图片数据
集、IMDB 文本数据集等。我们已经介绍过，不再敖述。

## 8.1.1 常见网络层类

对于常见的神经网络层，可以使用张量方式的底层接口函数来实现，这些接口函数一
般在 tf.nn 模块中。更常用地，对于常见的网络层，我们一般直接使用层方式来完成模型的
搭建，在 tf.keras.layers 命名空间(下文使用 layers 指代 tf.keras.layers)中提供了大量常见网络层的类，如全连接层、激活函数层、池化层、卷积层、循环神经网络层等。对于这些网络
层类，只需要在创建时指定网络层的相关参数，并调用__call__方法即可完成前向计算。在
调用__call__方法时，Keras 会自动调用每个层的前向传播逻辑，这些逻辑一般实现在类的
call 函数中。

以 Softmax 层为例，它既可以使用 tf.nn.softmax 函数在前向传播逻辑中完成 Softmax
运算，也可以通过 layers.Softmax(axis)类搭建 Softmax 网络层，其中 axis 参数指定进行
softmax 运算的维度。首先导入相关的子模块，实现如下：

In [1]:
import tensorflow as tf
# 导入 keras 模型，不能使用 import keras，它导入的是标准的 Keras 库
from tensorflow import keras
from tensorflow.keras import layers  # 导入常见网络层类

# 然后创建 Softmax 层，并调用__call__方法完成前向计算
x = tf.constant([[2., 1., 0.1]])  # 创建输入张量
layer = layers.Softmax(axis=-1)
out = layer(x)  # 调用 softmax 前向计算，输出为 out
out
# 经过 Softmax 网络层后，得到概率分布 out 为：

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.6590012 , 0.24243298, 0.09856589]], dtype=float32)>

In [2]:
# 当然，也可以直接通过 tf.nn.softmax()函数完成计算，代码如下
out = tf.nn.softmax(x)
out

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.6590012 , 0.24243298, 0.09856589]], dtype=float32)>

## 8.1.2 网络容器


对于常见的网络，需要手动调用每一层的类实例完成前向传播运算，当网络层数变得较深时，这一部分代码显得非常臃肿。可以通过 Keras 提供的网络容器 Sequential 将多个
网络层封装成一个大网络模型，只需要调用网络模型的实例一次即可完成数据从第一层到最末层的顺序传播运算。

In [4]:
# 导入Sequential 容器
from tensorflow.keras import Sequential, layers

network = Sequential(  # 封装为一个网络
    [
        layers.Dense(3, activation=None),  # 全连接层，此处不使用激活函数
        layers.ReLU(),  # 激活函数层
        layers.Dense(2, activation=None),  # 全连接层，此处不使用激活函数
        layers.ReLU()
    ]
)

x = tf.random.normal([4, 3])
out = network(x)
out

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>